### ISSUE TITLE
Custom Scroll bar hides behind header

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/one-pirate#7]
As I can see, we are using nicescroll js for this theme. But the scroll bar hides behind header and makes a bad UX.  Please fix it, or remove it completely.

**Comment by rodica-andronache** [comment]
Hi @suyogyashukla! Thanks for reporting this but we usually try to not update child themes unless there are major issues with them, because lots of users make changes to this child themes and at update they would loose the custom changes.
So, for this, maybe the best solution would be to create a doc of How to remove the custom scroll bar in OnePirate.
